export const COUNTRIES = [
  { flag: "🇦🇫", name: "Afghanistan", code: "+93", iso: "AF" },
  { flag: "🇦🇱", name: "Albania", code: "+355", iso: "AL" },
  { flag: "🇩🇿", name: "Algeria", code: "+213", iso: "DZ" },
  { flag: "🇦🇩", name: "Andorra", code: "+376", iso: "AD" },
  { flag: "🇦🇴", name: "Angola", code: "+244", iso: "AO" },
  { flag: "🇦🇷", name: "Argentina", code: "+54", iso: "AR" },
  { flag: "🇦🇲", name: "Armenia", code: "+374", iso: "AM" },
  { flag: "🇦🇺", name: "Australia", code: "+61", iso: "AU" },
  { flag: "🇦🇹", name: "Austria", code: "+43", iso: "AT" },
  { flag: "🇦🇿", name: "Azerbaijan", code: "+994", iso: "AZ" },
  { flag: "🇧🇭", name: "Bahrain", code: "+973", iso: "BH" },
  { flag: "🇧🇾", name: "Belarus", code: "+375", iso: "BY" },
  { flag: "🇧🇪", name: "Belgium", code: "+32", iso: "BE" },
  { flag: "🇧🇴", name: "Bolivia", code: "+591", iso: "BO" },
  { flag: "🇧🇦", name: "Bosnia & Herzegovina", code: "+387", iso: "BA" },
  { flag: "🇧🇷", name: "Brazil", code: "+55", iso: "BR" },
  { flag: "🇧🇳", name: "Brunei", code: "+673", iso: "BN" },
  { flag: "🇧🇬", name: "Bulgaria", code: "+359", iso: "BG" },
  { flag: "🇰🇭", name: "Cambodia", code: "+855", iso: "KH" },
  { flag: "🇨🇲", name: "Cameroon", code: "+237", iso: "CM" },
  { flag: "🇨🇦", name: "Canada", code: "+1", iso: "CA" },
  { flag: "🇨🇱", name: "Chile", code: "+56", iso: "CL" },
  { flag: "🇨🇳", name: "China", code: "+86", iso: "CN" },
  { flag: "🇨🇴", name: "Colombia", code: "+57", iso: "CO" },
  { flag: "🇨🇬", name: "Congo", code: "+242", iso: "CG" },
  { flag: "🇭🇷", name: "Croatia", code: "+385", iso: "HR" },
  { flag: "🇨🇾", name: "Cyprus", code: "+357", iso: "CY" },
  { flag: "🇨🇿", name: "Czech Republic", code: "+420", iso: "CZ" },
  { flag: "🇩🇰", name: "Denmark", code: "+45", iso: "DK" },
  { flag: "🇪🇬", name: "Egypt", code: "+20", iso: "EG" },
  { flag: "🇪🇪", name: "Estonia", code: "+372", iso: "EE" },
  { flag: "🇪🇹", name: "Ethiopia", code: "+251", iso: "ET" },
  { flag: "🇫🇮", name: "Finland", code: "+358", iso: "FI" },
  { flag: "🇫🇷", name: "France", code: "+33", iso: "FR" },
  { flag: "🇬🇪", name: "Georgia", code: "+995", iso: "GE" },
  { flag: "🇩🇪", name: "Germany", code: "+49", iso: "DE" },
  { flag: "🇬🇭", name: "Ghana", code: "+233", iso: "GH" },
  { flag: "🇬🇷", name: "Greece", code: "+30", iso: "GR" },
  { flag: "🇬🇹", name: "Guatemala", code: "+502", iso: "GT" },
  { flag: "🇭🇳", name: "Honduras", code: "+504", iso: "HN" },
  { flag: "🇭🇰", name: "Hong Kong", code: "+852", iso: "HK" },
  { flag: "🇭🇺", name: "Hungary", code: "+36", iso: "HU" },
  { flag: "🇮🇸", name: "Iceland", code: "+354", iso: "IS" },
  { flag: "🇮🇩", name: "Indonesia", code: "+62", iso: "ID" },
  { flag: "🇮🇷", name: "Iran", code: "+98", iso: "IR" },
  { flag: "🇮🇶", name: "Iraq", code: "+964", iso: "IQ" },
  { flag: "🇮🇪", name: "Ireland", code: "+353", iso: "IE" },
  { flag: "🇮🇱", name: "Israel", code: "+972", iso: "IL" },
  { flag: "🇮🇹", name: "Italy", code: "+39", iso: "IT" },
  { flag: "🇯🇲", name: "Jamaica", code: "+1-876", iso: "JM" },
  { flag: "🇯🇵", name: "Japan", code: "+81", iso: "JP" },
  { flag: "🇯🇴", name: "Jordan", code: "+962", iso: "JO" },
  { flag: "🇰🇿", name: "Kazakhstan", code: "+7", iso: "KZ" },
  { flag: "🇰🇪", name: "Kenya", code: "+254", iso: "KE" },
  { flag: "🇰🇼", name: "Kuwait", code: "+965", iso: "KW" },
  { flag: "🇰🇬", name: "Kyrgyzstan", code: "+996", iso: "KG" },
  { flag: "🇱🇦", name: "Laos", code: "+856", iso: "LA" },
  { flag: "🇱🇻", name: "Latvia", code: "+371", iso: "LV" },
  { flag: "🇱🇧", name: "Lebanon", code: "+961", iso: "LB" },
  { flag: "🇱🇾", name: "Libya", code: "+218", iso: "LY" },
  { flag: "🇱🇮", name: "Liechtenstein", code: "+423", iso: "LI" },
  { flag: "🇱🇹", name: "Lithuania", code: "+370", iso: "LT" },
  { flag: "🇱🇺", name: "Luxembourg", code: "+352", iso: "LU" },
  { flag: "🇲🇴", name: "Macau", code: "+853", iso: "MO" },
  { flag: "🇲🇾", name: "Malaysia", code: "+60", iso: "MY" },
  { flag: "🇲🇻", name: "Maldives", code: "+960", iso: "MV" },
  { flag: "🇲🇱", name: "Mali", code: "+223", iso: "ML" },
  { flag: "🇲🇹", name: "Malta", code: "+356", iso: "MT" },
  { flag: "🇲🇽", name: "Mexico", code: "+52", iso: "MX" },
  { flag: "🇲🇩", name: "Moldova", code: "+373", iso: "MD" },
  { flag: "🇲🇳", name: "Mongolia", code: "+976", iso: "MN" },
  { flag: "🇲🇦", name: "Morocco", code: "+212", iso: "MA" },
  { flag: "🇲🇿", name: "Mozambique", code: "+258", iso: "MZ" },
  { flag: "🇲🇲", name: "Myanmar", code: "+95", iso: "MM" },
  { flag: "🇳🇵", name: "Nepal", code: "+977", iso: "NP" },
  { flag: "🇳🇱", name: "Netherlands", code: "+31", iso: "NL" },
  { flag: "🇳🇿", name: "New Zealand", code: "+64", iso: "NZ" },
  { flag: "🇰🇵", name: "North Korea", code: "+850", iso: "KP" },
  { flag: "🇲🇰", name: "North Macedonia", code: "+389", iso: "MK" },
  { flag: "🇳🇴", name: "Norway", code: "+47", iso: "NO" },
  { flag: "🇴🇲", name: "Oman", code: "+968", iso: "OM" },
  { flag: "🇵🇰", name: "Pakistan", code: "+92", iso: "PK" },
  { flag: "🇵🇦", name: "Panama", code: "+507", iso: "PA" },
  { flag: "🇵🇬", name: "Papua New Guinea", code: "+675", iso: "PG" },
  { flag: "🇵🇾", name: "Paraguay", code: "+595", iso: "PY" },
  { flag: "🇵🇪", name: "Peru", code: "+51", iso: "PE" },
  { flag: "🇵🇭", name: "Philippines", code: "+63", iso: "PH" },
  { flag: "🇵🇱", name: "Poland", code: "+48", iso: "PL" },
  { flag: "🇵🇹", name: "Portugal", code: "+351", iso: "PT" },
  { flag: "🇶🇦", name: "Qatar", code: "+974", iso: "QA" },
  { flag: "🇷🇴", name: "Romania", code: "+40", iso: "RO" },
  { flag: "🇷🇺", name: "Russia", code: "+7", iso: "RU" },
  { flag: "🇷🇼", name: "Rwanda", code: "+250", iso: "RW" },
  { flag: "🇸🇦", name: "Saudi Arabia", code: "+966", iso: "SA" },
  { flag: "🇸🇳", name: "Senegal", code: "+221", iso: "SN" },
  { flag: "🇷🇸", name: "Serbia", code: "+381", iso: "RS" },
  { flag: "🇸🇬", name: "Singapore", code: "+65", iso: "SG" },
  { flag: "🇸🇰", name: "Slovakia", code: "+421", iso: "SK" },
  { flag: "🇸🇮", name: "Slovenia", code: "+386", iso: "SI" },
  { flag: "🇸🇴", name: "Somalia", code: "+252", iso: "SO" },
  { flag: "🇿🇦", name: "South Africa", code: "+27", iso: "ZA" },
  { flag: "🇰🇷", name: "South Korea", code: "+82", iso: "KR" },
  { flag: "🇸🇸", name: "South Sudan", code: "+211", iso: "SS" },
  { flag: "🇪🇸", name: "Spain", code: "+34", iso: "ES" },
  { flag: "🇸🇩", name: "Sudan", code: "+249", iso: "SD" },
  { flag: "🇸🇪", name: "Sweden", code: "+46", iso: "SE" },
  { flag: "🇨🇭", name: "Switzerland", code: "+41", iso: "CH" },
  { flag: "🇸🇾", name: "Syria", code: "+963", iso: "SY" },
  { flag: "🇹🇼", name: "Taiwan", code: "+886", iso: "TW" },
  { flag: "🇹🇯", name: "Tajikistan", code: "+992", iso: "TJ" },
  { flag: "🇹🇿", name: "Tanzania", code: "+255", iso: "TZ" },
  { flag: "🇹🇭", name: "Thailand", code: "+66", iso: "TH" },
  { flag: "🇹🇱", name: "Timor-Leste", code: "+670", iso: "TL" },
  { flag: "🇹🇳", name: "Tunisia", code: "+216", iso: "TN" },
  { flag: "🇹🇷", name: "Turkey", code: "+90", iso: "TR" },
  { flag: "🇹🇲", name: "Turkmenistan", code: "+993", iso: "TM" },
  { flag: "🇺🇦", name: "Ukraine", code: "+380", iso: "UA" },
  { flag: "🇦🇪", name: "UAE", code: "+971", iso: "AE" },
  { flag: "🇬🇧", name: "United Kingdom", code: "+44", iso: "GB" },
  { flag: "🇺🇸", name: "United States", code: "+1", iso: "US" },
  { flag: "🇺🇾", name: "Uruguay", code: "+598", iso: "UY" },
  { flag: "🇺🇿", name: "Uzbekistan", code: "+998", iso: "UZ" },
  { flag: "🇻🇪", name: "Venezuela", code: "+58", iso: "VE" },
  { flag: "🇻🇳", name: "Vietnam", code: "+84", iso: "VN" },
  { flag: "🇾🇪", name: "Yemen", code: "+967", iso: "YE" },
  { flag: "🇿🇲", name: "Zambia", code: "+260", iso: "ZM" },
];
