"use client";

import { TaskStatus, useTasks } from "~~/utils/lib/helper/useGetLoopTask";

const formatValue = (value: any) => {
  if (typeof value === "bigint") {
    return value.toString();
  }

  if (Array.isArray(value)) {
    return JSON.stringify(
      value,
      (_, v) => (typeof v === "bigint" ? v.toString() : v),
      2,
    );
  }

  if (typeof value === "object" && value !== null) {
    return JSON.stringify(
      value,
      (_, v) => (typeof v === "bigint" ? v.toString() : v),
      2,
    );
  }

  return String(value);
};

const TaskCard = ({ task }: { task: any }) => {
  return (
    <div className="card bg-base-200 shadow">
      <div className="card-body">
        <h3 className="card-title">
          {task.title || `Task #${task.taskId?.toString()}`}
        </h3>

        <div className="space-y-2">
          {Object.entries(task).map(([key, value]) => {
            // Skip numeric indexes generated by Solidity tuple returns
            if (!isNaN(Number(key))) return null;

            return (
              <div
                key={key}
                className="flex flex-col border-b border-base-300 pb-2"
              >
                <span className="font-semibold text-primary">
                  {key}
                </span>

                <span className="break-all text-sm">
                  {key === "status"
                    ? TaskStatus[Number(value)]
                    : formatValue(value)}
                </span>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

const TasksPage = () => {
  const {
    tasks,
    taskCounter,

    creatorTasks,
    latestCreatorTask,

    activeTasks,
    completedTasks,

    getTasksByStatus,
    loading,
  } = useTasks();

  const openRegistrationTasks = getTasksByStatus(
    TaskStatus.OpenRegistration,
  );

  if (loading.isLoading) {
    return (
      <div className="p-6 flex justify-center">
        <span className="loading loading-spinner loading-lg" />
      </div>
    );
  }

  return (
    <div className="container mx-auto p-6 space-y-10">
      <h1 className="text-4xl font-bold">
        Tasks Dashboard
      </h1>

      {/* Stats */}
      <div className="stats shadow w-full">
        <div className="stat">
          <div className="stat-title">Task Counter</div>
          <div className="stat-value">
            {taskCounter?.toString() ?? 0}
          </div>
        </div>

        <div className="stat">
          <div className="stat-title">Total Tasks</div>
          <div className="stat-value">
            {tasks.length}
          </div>
        </div>

        <div className="stat">
          <div className="stat-title">Active</div>
          <div className="stat-value">
            {activeTasks.length}
          </div>
        </div>

        <div className="stat">
          <div className="stat-title">Completed</div>
          <div className="stat-value">
            {completedTasks.length}
          </div>
        </div>
      </div>

      {/* Latest Creator Task */}
      {latestCreatorTask && (
        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Latest My Task
          </h2>

          <TaskCard task={latestCreatorTask} />
        </section>
      )}

      {/* My Tasks */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">
          My Tasks ({creatorTasks.length})
        </h2>

        <div className="grid gap-4">
          {creatorTasks.map(task => (
            <TaskCard
              key={task.taskId?.toString()}
              task={task}
            />
          ))}
        </div>
      </section>

      {/* Active Tasks */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">
          Active Tasks ({activeTasks.length})
        </h2>

        <div className="grid gap-4">
          {activeTasks.map(task => (
            <TaskCard
              key={task.taskId?.toString()}
              task={task}
            />
          ))}
        </div>
      </section>

      {/* Open Registration */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">
          Open Registration Tasks (
          {openRegistrationTasks.length})
        </h2>

        <div className="grid gap-4">
          {openRegistrationTasks.map(task => (
            <TaskCard
              key={task.taskId?.toString()}
              task={task}
            />
          ))}
        </div>
      </section>

      {/* Completed */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">
          Completed Tasks ({completedTasks.length})
        </h2>

        <div className="grid gap-4">
          {completedTasks.map(task => (
            <TaskCard
              key={task.taskId?.toString()}
              task={task}
            />
          ))}
        </div>
      </section>

      {/* ALL RAW TASKS */}
      <section>
        <h2 className="text-2xl font-semibold mb-4">
          All Tasks ({tasks.length})
        </h2>

        <div className="grid gap-4">
          {tasks.map(task => (
            <TaskCard
              key={task.taskId?.toString()}
              task={task}
            />
          ))}
        </div>
      </section>
    </div>
  );
};

export default TasksPage;